web:
  build: .
  volumes: &app_volumes
    - .:/app
    - ~/.ssh:/root/.ssh
    - ~/.bash_history:/root/.bash_history
  volumes_from:
    - bundle_cache
  ports:
    - 3000:3000
  links: &app_links
    - db
    - redis
  env_file:
    - web.env
    - secrets.env

db:
  image: postgres:9.6

bundle_cache:
  image: busybox
  volumes:
    - /bundle_cache

redis:
  image: redis:3.0
