version: '2'

services:
  web:
    build: .
    volumes:
      - .:/app
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts:rw
      - ~/.bash_history:/root/.bash_history
      - ~/.gitconfig:/root/.gitconfig:ro
      - bundle_cache:/usr/local/bundle
    ports:
      - 3000:3000
    links:
      - db
      - redis
    env_file:
      - web.env
      - secrets.env

  db:
    image: postgres:9.6

  redis:
    image: redis:3.0

volumes:
  bundle_cache:
