closest_menus_date_offset: 2
domain: obeder.restream.pro
freeze_user_menu_at: '15:00'
redis:
  host: <%= ENV['REDIS_HOST'] || '127.0.0.1' %>
  port: <%= ENV['REDIS_PORT'] || 6379 %>
  sidekiq_db: <%= ENV['REDIS_DB'] || 'db0' %>
